name: mobile_app_inventory_system
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1  
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^2.6.1 
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  freezed: ^3.2.3
  firebase_core: ^4.2.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_auth: ^6.1.1
  mockito: ^5.5.1
  cloud_firestore: ^6.0.3
  uuid: ^4.5.1
  image_picker: ^1.0.4
  firebase_storage: 13.0.3
  provider: ^6.1.5+1
  flutter_native_splash: ^2.4.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.1

dependency_overrides:
  analyzer: ^6.0.0

flutter:
  uses-material-design: true